### ISSUE TITLE
Don't start in development mode by default

### ISSUE THREAD

**Issue by trieloff** [funcool/catacumba#16]
Catacumba should not start in development mode by default, because it adds complexity for people running it in production. Following the principles of:
- Explicit is better than implicit.
- Simple is better than complex.
We should make the debug mode an explicit choice (instead of an implicit default) and make it simple to run and operate catacumba

**Comment by trieloff** [comment]
Patch provided in #17

**Comment by niwinz** [comment]
Merged!
