### ISSUE TITLE
cookie as session store

### ISSUE THREAD

**Issue by prepor** [funcool/catacumba#31]
Hello! How to implement signed-cookie based session store? For setup cookies we need access to context or use returned value from write-session as new session key (like ring session stores).

**Comment by niwinz** [comment]
Hmm. The current design does not allows that, so I think we can rethink it and improve it for the next version.

**Comment by niwinz** [comment]
The session storage is refactored and will be available on the next version (0.8.0) if you want hack with it you can use the `0.8.0-SNAPSHOT`.

Also, a jws cookie signed storage is implemented.
