### ISSUE TITLE
:assets as root resource

### ISSUE THREAD

**Issue by moea** [funcool/catacumba#34]
I'm experimenting with Catacumba, and likely doing something wrong.  This route entry:

`[:assets "x" {:dir "public" :indexes ["index.html"]}]`

Behaves as I would expect, when I visit `/x` (provided I've a .catacumba in `resources/`).  This one:

`[:assets "" {:dir "public" :indexes ["index.html"]}]`

Only serves the index page at `/`, with a 404 for any static child resources (CSS, JS, in this case).  How would I go about serving static content at the root of the resource tree?  Please excuse me if I've missed something obvious.

**Comment by niwinz** [comment]
It there is a bug just in that case! Thanks for notice me! This kind of use case is not tested because I didn't expect it.

**Comment by niwinz** [comment]
You can use the `0.9.0-SNAPSHOT` release from clojars for now.

**Comment by moea** [comment]
Thanks! I'll take a look.
