### ISSUE TITLE
Request logging support

### ISSUE THREAD

**Issue by niwinz** [funcool/catacumba#35]

**Comment by moea** [comment]
How do you see this working differently to something like:

```clojure
[:any (ratpack.handling.RequestLogger/ncsa)]
```
I'd be more than happy to take a stab at it, if you outline what you're imagining.

**Comment by niwinz** [comment]
Ho @moea 
The main idea of this issue is provide a "clojury" api for it, one just wrap the ratpack.handling.RequestLogger/ncsa and other providing some kind of api for allow the user log in different logger or provide more information.

I imagine something like:

```
(require '[catacumba.handlers.logging :as logging])

[:any (logging/handler)]

;; and 

(defn my-logger-fn
  [logger-context]
  (println (:method logger-context) "-" (:path logger-context))))

[:any (logging/handler my-logger-fn)]
```

The `logger-context` may be a hash-map with limited set of usefull keys generated from http://ratpack.io/manual/current/api/ratpack/handling/RequestOutcome.html
