### ISSUE TITLE
Best way to get a Guice registry in?

### ISSUE THREAD

**Issue by christoph-frick** [funcool/catacumba#41]
I currently use `attach-route`, but reaching into the `impl` namespace feels somewhat unclean.

    (defmethod catacumba.impl.routing/attach-route :guice-registry
      [^Chain chain [_ binding-spec]]
      (.register chain
                 (.apply
                  (Guice/registry ^Action (ch/fn->action ^BindingsSpec binding-spec))
                  (.getRegistry chain))))

I saw now way to do it in :setup and the initial creation of the registry is done in a private fn.

**Comment by niwinz** [comment]
Hmm, setup I think should be the way to do that. Can you explain that are you doing? I'm not very familiar with guice, sorry. Maybe the current approach for setup is not enough and can be improved.

**Comment by christoph-frick** [comment]
I am fooling around with PAC4J and it needs the Guice module `SessionModule` in place. So when setting up the server, the way to do this would be `.registry(Guice.registry(b -> b.module(ServiceModule.class)))` (see https://ratpack.io/manual/current/api/ratpack/guice/Guice.html). I have not found a way to make Guice play nicely with the `RegistryBuilder` I get passed down in `:setup`.  From what I have seen, adding it in the Chain is not that bad - it's basically the same as with e.g. `:error`.

**Comment by niwinz** [comment]
Hmm, sure, the setup at this moment does not allows do that. I will think about that for ASAP improve!

An other option for solve your problem can be define a handler. Let see some example (not tested):

```clojure

(defn guice
  [binding-spec]
  (reify ratpack.handling.Handler
    (^void handle [_ ^Context ctx]
     (let [registry (Guice/registry
                     (ch/fn->action binding-spec))]
       (.next registry)))))

(def app
  (ct/routes [[:all (guice here-your-specs)]
              [... here your routes]]))

;; or

(def server (ct/run-server your-routes
                           {:decorators [(guice here-your-specs)]
                            :port 3030}))
```

**Comment by niwinz** [comment]
After some time researching, ratpack only offers two exclusive way to setup registry (using `.registry` method or `.registryOf`). Catacumba already uses `.registryOf` so if I provide access for use the `.register` method in setup hook, it can overwrite catacumba's stuff and that is not desired.

At this moment the best way to do it then is using the proposted solution.

**Comment by christoph-frick** [comment]
thanks for looking into it
