### ISSUE TITLE
Websocket example

### ISSUE THREAD

**Issue by benjyz** [funcool/catacumba#44]
Tried to get the websocket example running.

Replaced ```[catacumba.handlers :as hs]``` with ```[catacumba.handlers.misc :as hs]```
in the namesspace ```websocket-echo.core```

Then in the browser I get

`WebSocket connection to 'ws://localhost:5050/ws' failed: Error during WebSocket handshake: Unexpected response code: 200
`

**Comment by niwinz** [comment]
This is already fixed! Thanks for report.
