### ISSUE TITLE
Http cache handling

### ISSUE THREAD

**Issue by niwinz** [funcool/catacumba#55]
It depends on ratpack stuff that is not implement at this moment.

**Comment by kardan** [comment]
Relevant Ratpack issue https://github.com/ratpack/ratpack/issues/941

**Comment by niwinz** [comment]
I think I have a solution for this outside of ratpack, so in this days I'll try to take some time for implement it.

**Comment by niwinz** [comment]
After thinkg over it I think there are no generic impl that fits very well with the bunch of heterogeneous response output types support that catacumba has... having a generic way to handle http cache will take too much asumptions and I don't want to take that decisions for the user.

However, catacumba already has good abstraction for extend it and put the httpcache stuff when the user wants. I have implemented the etag http-cache in uxbox repository just using a custom response body type, that implements the catacumba body abstraction and implements the etag stuff:
https://github.com/uxbox/uxbox-backend/blob/0e5cb6611e893cd15b6076ea81fe335c53b03385/src/uxbox/util/response.clj#L27

In the same way, the content negotiation can be also implemented. 

So for the moment I'll close this issue because I think it can be solved diretly by the user using a proper impl that the user needs for it application.

**Comment by kardan** [comment]
👍
